--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.addresses (
                                  id bigint NOT NULL,
                                  address_line character varying(255) NOT NULL,
                                  city character varying(100) NOT NULL,
                                  country character varying(100) NOT NULL,
                                  created_at timestamp(6) without time zone NOT NULL,
                                  pin_code character varying(6) NOT NULL,
                                  state character varying(100) NOT NULL,
                                  updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_versions (
                                     id bigint NOT NULL,
                                     created_at timestamp(6) without time zone NOT NULL,
                                     latest_version character varying(255) NOT NULL,
                                     message text,
                                     min_build_number integer NOT NULL,
                                     min_supported_version character varying(255) NOT NULL,
                                     platform character varying(255) NOT NULL,
                                     release_notes text,
                                     rollout_percentage integer NOT NULL,
                                     store_url character varying(255) NOT NULL,
                                     updated_at timestamp(6) without time zone NOT NULL,
                                     CONSTRAINT app_versions_platform_check CHECK (((platform)::text = ANY ((ARRAY['ANDROID'::character varying, 'IOS'::character varying])::text[])))
);


--
-- Name: app_versions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bank_details (
                                     id bigint NOT NULL,
                                     account_number character varying(255) NOT NULL,
                                     account_type character varying(255) NOT NULL,
                                     bank_name character varying(255),
                                     ifsc_code character varying(255) NOT NULL,
                                     is_primary boolean NOT NULL,
                                     payment_ref bigint,
                                     ref_id character varying(255),
                                     investor_id bigint,
                                     user_id bigint NOT NULL,
                                     CONSTRAINT bank_details_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['SAVINGS'::character varying, 'CURRENT'::character varying])::text[])))
);


--
-- Name: bank_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bank_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: basket_fund; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.basket_fund (
                                    basket_id bigint NOT NULL,
                                    fund_id bigint NOT NULL,
                                    allocation_percentage double precision NOT NULL
);


--
-- Name: baskets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.baskets (
                                id bigint NOT NULL,
                                created_at timestamp(6) without time zone NOT NULL,
                                returns double precision,
                                title character varying(255) NOT NULL,
                                updated_at timestamp(6) without time zone NOT NULL,
                                years double precision,
                                basket_type character varying(255) DEFAULT 'EDUCATION'::character varying NOT NULL
);


--
-- Name: baskets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.baskets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.baskets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: children; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.children (
                                 id bigint NOT NULL,
                                 created_at timestamp(6) without time zone NOT NULL,
                                 date_of_birth date NOT NULL,
                                 first_name character varying(255) NOT NULL,
                                 gender character varying(255) NOT NULL,
                                 invest_under_child boolean NOT NULL,
                                 last_name character varying(255),
                                 updated_at timestamp(6) without time zone NOT NULL,
                                 investor_id bigint,
                                 user_id bigint NOT NULL,
                                 is_deleted boolean DEFAULT false NOT NULL,
                                 deleted_at timestamp without time zone,
                                 CONSTRAINT children_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'TRANSGENDER'::character varying])::text[])))
);


--
-- Name: children_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.children ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.children_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
                                  id bigint NOT NULL,
                                  content_type character varying(255) NOT NULL,
                                  created_at timestamp(6) without time zone NOT NULL,
                                  file_name character varying(255) NOT NULL,
                                  file_size bigint NOT NULL,
                                  s3key character varying(255) NOT NULL,
                                  updated_at timestamp(6) without time zone NOT NULL,
                                  user_id character varying(255) NOT NULL,
                                  visibility character varying(255) NOT NULL,
                                  CONSTRAINT documents_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[])))
);


--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: education; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.education (
                                  id bigint NOT NULL,
                                  category character varying(255),
                                  country character varying(255) NOT NULL,
                                  expected_fee double precision NOT NULL,
                                  expected_increase_percent_gt10yr double precision NOT NULL,
                                  expected_increase_percent_lt10yr double precision NOT NULL,
                                  last_year_fee double precision NOT NULL,
                                  name character varying(255) NOT NULL,
                                  type character varying(255) NOT NULL,
                                  CONSTRAINT education_type_check CHECK (((type)::text = ANY ((ARRAY['INSTITUTION'::character varying, 'COURSE'::character varying])::text[])))
);


--
-- Name: education_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.education ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.education_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: folio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.folio (
                              id bigint NOT NULL,
                              ref character varying(255) NOT NULL,
                              fund_id bigint,
                              investor_id bigint,
                              user_id bigint NOT NULL
);


--
-- Name: folio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.folio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.folio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: funds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.funds (
                              id bigint NOT NULL,
                              amc_code character varying(255),
                              created_at timestamp(6) without time zone NOT NULL,
                              description character varying(255),
                              is_active boolean NOT NULL,
                              isin_code character varying(255),
                              label character varying(255) NOT NULL,
                              mim_purchase_amount double precision NOT NULL,
                              min_sip_amount double precision NOT NULL,
                              name character varying(255) NOT NULL,
                              nav double precision NOT NULL,
                              nav_date timestamp(6) without time zone NOT NULL,
                              scheme_type character varying(255),
                              updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: funds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.funds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.funds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goals (
                              id bigint NOT NULL,
                              created_at timestamp(6) without time zone NOT NULL,
                              current_amount double precision NOT NULL,
                              monthly_sip double precision,
                              status character varying(255) NOT NULL,
                              target_amount double precision NOT NULL,
                              target_date date NOT NULL,
                              title character varying(255) NOT NULL,
                              updated_at timestamp(6) without time zone NOT NULL,
                              basket_id bigint,
                              child_id bigint,
                              education_id bigint,
                              user_id bigint NOT NULL,
                              invested_amount double precision DEFAULT 0.0 NOT NULL,
                              is_deleted boolean DEFAULT false NOT NULL,
                              deleted_at timestamp without time zone,
                              transferred_to_goal_id bigint,
                              CONSTRAINT goals_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PAYMENT_PENDING'::character varying, 'ACTIVE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: goals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: holdings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.holdings (
                                 id bigint NOT NULL,
                                 created_at timestamp(6) without time zone NOT NULL,
                                 current_value double precision NOT NULL,
                                 invested_amount double precision NOT NULL,
                                 order_allocation_percentage double precision NOT NULL,
                                 units double precision NOT NULL,
                                 updated_at timestamp(6) without time zone NOT NULL,
                                 child_id bigint,
                                 fund_id bigint,
                                 goal_id bigint,
                                 order_id bigint,
                                 user_id bigint NOT NULL
);


--
-- Name: holdings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.holdings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holdings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: investors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.investors (
                                  id bigint NOT NULL,
                                  account_ref character varying(255),
                                  created_at timestamp(6) without time zone NOT NULL,
                                  e_sign_request_ref character varying(255),
                                  kyc_request_ref character varying(255),
                                  ref character varying(255),
                                  type character varying(255) NOT NULL,
                                  updated_at timestamp(6) without time zone NOT NULL,
                                  CONSTRAINT investors_type_check CHECK (((type)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'MINOR'::character varying])::text[])))
);


--
-- Name: investors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.investors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_history (
                                    id bigint NOT NULL,
                                    duration_ms bigint,
                                    end_time timestamp(6) without time zone,
                                    error_message text,
                                    job_name character varying(255) NOT NULL,
                                    start_time timestamp(6) without time zone NOT NULL,
                                    status character varying(255) NOT NULL,
                                    trigger_name character varying(255),
                                    CONSTRAINT job_history_status_check CHECK (((status)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAILURE'::character varying])::text[])))
);


--
-- Name: job_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.job_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mfa_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mfa_attempts (
                                     id bigint NOT NULL,
                                     mfa_session_id uuid NOT NULL,
                                     attempted_at timestamp without time zone DEFAULT now() NOT NULL,
                                     success boolean NOT NULL,
                                     ip_address character varying(255),
                                     user_agent text
);


--
-- Name: TABLE mfa_attempts; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.mfa_attempts IS 'Tracks OTP verification attempts for audit and security purposes';


--
-- Name: mfa_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.mfa_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: mfa_attempts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.mfa_attempts_id_seq OWNED BY public.mfa_attempts.id;


--
-- Name: mfa_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mfa_sessions (
                                     id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
                                     user_id character varying(64) NOT NULL,
                                     action character varying(50) NOT NULL,
                                     channel character varying(20) NOT NULL,
                                     destination character varying(64),
                                     otp_hash character varying(64) NOT NULL,
                                     otp_expires_at timestamp without time zone NOT NULL,
                                     max_attempts smallint DEFAULT 3 NOT NULL,
                                     attempts smallint DEFAULT 0 NOT NULL,
                                     status character varying(20) NOT NULL,
                                     device_id character varying(64),
                                     ip_address character varying(255),
                                     user_agent text,
                                     mfa_token text,
                                     mfa_token_expires_at timestamp without time zone,
                                     verified_at timestamp without time zone,
                                     created_at timestamp without time zone DEFAULT now() NOT NULL,
                                     CONSTRAINT chk_mfa_sessions_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'EXPIRED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: TABLE mfa_sessions; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.mfa_sessions IS 'Stores MFA sessions with OTP hashes and verification status';


--
-- Name: nominee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nominee (
                                id bigint NOT NULL,
                                allocation integer NOT NULL,
                                created_at timestamp(6) without time zone NOT NULL,
                                dob timestamp(6) without time zone NOT NULL,
                                email character varying(255),
                                guardian_name character varying(255),
                                mobile_number character varying(255) NOT NULL,
                                name character varying(255) NOT NULL,
                                pan character varying(255),
                                ref character varying(255),
                                relationship character varying(255) NOT NULL,
                                updated_at timestamp(6) without time zone NOT NULL,
                                nominee_address_id bigint,
                                user_id bigint NOT NULL,
                                CONSTRAINT nominee_relationship_check CHECK (((relationship)::text = ANY ((ARRAY['FATHER'::character varying, 'MOTHER'::character varying, 'AUNT'::character varying, 'BROTHER'::character varying, 'BROTHER_IN_LAW'::character varying, 'DAUGHTER'::character varying, 'DAUGHTER_IN_LAW'::character varying, 'FATHER_IN_LAW'::character varying, 'GRAND_DAUGHTER'::character varying, 'GRAND_FATHER'::character varying, 'GRAND_MOTHER'::character varying, 'GRAND_SON'::character varying, 'MOTHER_IN_LAW'::character varying, 'NEPHEW'::character varying, 'NIECE'::character varying, 'SISTER'::character varying, 'SISTER_IN_LAW'::character varying, 'SON'::character varying, 'SON_IN_LAW'::character varying, 'SPOUSE'::character varying, 'UNCLE'::character varying, 'OTHER'::character varying, 'COURT_APPOINTED_LEGAL_GUARDIAN'::character varying])::text[])))
);


--
-- Name: nominee_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nominee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nominee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
                                    id bigint NOT NULL,
                                    amount double precision NOT NULL,
                                    payment_ref bigint,
                                    processing_state character varying(255),
                                    ref character varying(255),
                                    unit_price double precision,
                                    units double precision,
                                    version bigint,
                                    fund_id bigint,
                                    order_id bigint,
                                    user_id bigint NOT NULL,
                                    status character varying(255),
                                    last_processed_transaction_ref character varying(255)
);


--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
                               dtype character varying(31) NOT NULL,
                               id bigint NOT NULL,
                               amount double precision,
                               created_at timestamp(6) without time zone NOT NULL,
                               updated_at timestamp(6) without time zone NOT NULL,
                               end_date date,
                               failure_count integer,
                               frequency character varying(255),
                               is_active boolean,
                               last_attempt_at timestamp(6) without time zone,
                               last_order_ref character varying(255),
                               last_provider_transaction_id character varying(255),
                               next_run_date date,
                               schedule_status character varying(255),
                               step_up_amount double precision,
                               step_up_end_date date,
                               step_up_frequency character varying(255),
                               step_up_start_date date,
                               start_date date,
                               reason character varying(255),
                               goal_id bigint,
                               investor_id bigint,
                               payment_id bigint,
                               user_id bigint NOT NULL,
                               is_placed boolean DEFAULT false,
                               CONSTRAINT orders_frequency_check CHECK (((frequency)::text = 'MONTHLY'::text)),
    CONSTRAINT orders_schedule_status_check CHECK (((schedule_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'RUNNING'::character varying, 'ERROR'::character varying, 'COMPLETED'::character varying, 'PAUSED'::character varying])::text[]))),
    CONSTRAINT orders_step_up_frequency_check CHECK (((step_up_frequency)::text = ANY ((ARRAY['MONTHLY'::character varying, 'QUARTERLY'::character varying, 'HALF_YEARLY'::character varying, 'YEARLY'::character varying])::text[])))
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
                                 id bigint NOT NULL,
                                 buy_status character varying(255) NOT NULL,
                                 created_at timestamp(6) without time zone NOT NULL,
                                 mandate_confirmation_url character varying(255),
                                 mandateid bigint,
                                 mandate_ref character varying(255),
                                 order_ref character varying(255),
                                 payment_type character varying(255),
                                 payment_url character varying(255),
                                 ref character varying(255),
                                 sip_status character varying(255) NOT NULL,
                                 updated_at timestamp(6) without time zone NOT NULL,
                                 upi_id character varying(255),
                                 verification_ref character varying(255),
                                 verification_status character varying(255) NOT NULL,
                                 bank_id bigint,
                                 child_id bigint,
                                 investor_id bigint NOT NULL,
                                 user_id bigint NOT NULL,
                                 buy_submitted_at timestamp(6) without time zone,
                                 sip_submitted_at timestamp(6) without time zone,
                                 CONSTRAINT payments_buy_status_check CHECK (((buy_status)::text = ANY ((ARRAY['NOT_AVAILABLE'::character varying, 'PENDING'::character varying, 'SUBMITTED'::character varying, 'ACTIVE'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT payments_payment_type_check CHECK (((payment_type)::text = ANY ((ARRAY['NET_BANKING'::character varying, 'UPI'::character varying])::text[]))),
    CONSTRAINT payments_sip_status_check CHECK (((sip_status)::text = ANY ((ARRAY['NOT_AVAILABLE'::character varying, 'PENDING'::character varying, 'SUBMITTED'::character varying, 'ACTIVE'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT payments_verification_status_check CHECK (((verification_status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qrtz_blob_triggers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qrtz_blob_triggers (
                                           sched_name character varying(120) NOT NULL,
                                           trigger_name character varying(200) NOT NULL,
                                           trigger_group character varying(200) NOT NULL,
                                           blob_data bytea
);


--
-- Name: qrtz_calendars; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qrtz_calendars (
                                       sched_name character varying(120) NOT NULL,
                                       calendar_name character varying(200) NOT NULL,
                                       calendar bytea NOT NULL
);


--
-- Name: qrtz_cron_triggers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qrtz_cron_triggers (
                                           sched_name character varying(120) NOT NULL,
                                           trigger_name character varying(200) NOT NULL,
                                           trigger_group character varying(200) NOT NULL,
                                           cron_expression character varying(120) NOT NULL,
                                           time_zone_id character varying(80)
);


--
-- Name: qrtz_fired_triggers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qrtz_fired_triggers (
                                            sched_name character varying(120) NOT NULL,
                                            entry_id character varying(95) NOT NULL,
                                            trigger_name character varying(200) NOT NULL,
                                            trigger_group character varying(200) NOT NULL,
                                            instance_name character varying(200) NOT NULL,
                                            fired_time bigint NOT NULL,
                                            sched_time bigint NOT NULL,
                                            priority integer NOT NULL,
                                            state character varying(16) NOT NULL,
                                            job_name character varying(200),
                                            job_group character varying(200),
                                            is_nonconcurrent boolean,
                                            requests_recovery boolean
);


--
-- Name: qrtz_job_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qrtz_job_details (
                                         sched_name character varying(120) NOT NULL,
                                         job_name character varying(200) NOT NULL,
                                         job_group character varying(200) NOT NULL,
                                         description character varying(250),
                                         job_class_name character varying(250) NOT NULL,
                                         is_durable boolean NOT NULL,
                                         is_nonconcurrent boolean NOT NULL,
                                         is_update_data boolean NOT NULL,
                                         requests_recovery boolean NOT NULL,
                                         job_data bytea
);


--
-- Name: qrtz_locks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qrtz_locks (
                                   sched_name character varying(120) NOT NULL,
                                   lock_name character varying(40) NOT NULL
);


--
-- Name: qrtz_paused_trigger_grps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qrtz_paused_trigger_grps (
                                                 sched_name character varying(120) NOT NULL,
                                                 trigger_group character varying(200) NOT NULL
);


--
-- Name: qrtz_scheduler_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qrtz_scheduler_state (
                                             sched_name character varying(120) NOT NULL,
                                             instance_name character varying(200) NOT NULL,
                                             last_checkin_time bigint NOT NULL,
                                             checkin_interval bigint NOT NULL
);


--
-- Name: qrtz_simple_triggers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qrtz_simple_triggers (
                                             sched_name character varying(120) NOT NULL,
                                             trigger_name character varying(200) NOT NULL,
                                             trigger_group character varying(200) NOT NULL,
                                             repeat_count bigint NOT NULL,
                                             repeat_interval bigint NOT NULL,
                                             times_triggered bigint NOT NULL
);


--
-- Name: qrtz_simprop_triggers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qrtz_simprop_triggers (
                                              sched_name character varying(120) NOT NULL,
                                              trigger_name character varying(200) NOT NULL,
                                              trigger_group character varying(200) NOT NULL,
                                              str_prop_1 character varying(512),
                                              str_prop_2 character varying(512),
                                              str_prop_3 character varying(512),
                                              int_prop_1 integer,
                                              int_prop_2 integer,
                                              long_prop_1 bigint,
                                              long_prop_2 bigint,
                                              dec_prop_1 numeric(13,4),
                                              dec_prop_2 numeric(13,4),
                                              bool_prop_1 boolean,
                                              bool_prop_2 boolean
);


--
-- Name: qrtz_triggers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qrtz_triggers (
                                      sched_name character varying(120) NOT NULL,
                                      trigger_name character varying(200) NOT NULL,
                                      trigger_group character varying(200) NOT NULL,
                                      job_name character varying(200) NOT NULL,
                                      job_group character varying(200) NOT NULL,
                                      description character varying(250),
                                      next_fire_time bigint,
                                      prev_fire_time bigint,
                                      priority integer,
                                      trigger_state character varying(16) NOT NULL,
                                      trigger_type character varying(8) NOT NULL,
                                      start_time bigint NOT NULL,
                                      end_time bigint,
                                      calendar_name character varying(200),
                                      misfire_instr smallint,
                                      job_data bytea
);


--
-- Name: reverse_penny_drops; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reverse_penny_drops (
                                            id bigint NOT NULL,
                                            reference_id character varying(255),
                                            status character varying(255) NOT NULL,
                                            transaction_id character varying(255),
                                            transaction_note character varying(255),
                                            user_id bigint,
                                            CONSTRAINT reverse_penny_drops_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: reverse_penny_drops_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reverse_penny_drops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reverse_penny_drops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sip_modification_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sip_modification_items (
                                               id bigint NOT NULL,
                                               new_amount double precision NOT NULL,
                                               old_amount double precision NOT NULL,
                                               status character varying(255) NOT NULL,
                                               modification_id bigint NOT NULL,
                                               order_item_id bigint NOT NULL,
                                               CONSTRAINT sip_modification_items_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: sip_modification_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sip_modification_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sip_modification_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sip_modifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sip_modifications (
                                          id bigint NOT NULL,
                                          created_at timestamp(6) without time zone NOT NULL,
                                          mandate_id bigint,
                                          requested_amount double precision NOT NULL,
                                          status character varying(255) NOT NULL,
                                          sip_order_id bigint NOT NULL,
                                          CONSTRAINT sip_modifications_status_check CHECK (((status)::text = ANY ((ARRAY['AWAITING_MANDATE'::character varying, 'PENDING'::character varying, 'CONFIRMING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: sip_modifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sip_modifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sip_modifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
                                     id bigint NOT NULL,
                                     amount double precision NOT NULL,
                                     created_at timestamp(6) without time zone NOT NULL,
                                     executed_at timestamp(6) without time zone NOT NULL,
                                     external_ref character varying(255),
                                     provider_transaction_id character varying(255),
                                     source_order_item_id bigint,
                                     status character varying(255) NOT NULL,
                                     type character varying(255) NOT NULL,
                                     unit_price double precision NOT NULL,
                                     units double precision NOT NULL,
                                     updated_at timestamp(6) without time zone NOT NULL,
                                     folio_id bigint,
                                     fund_id bigint NOT NULL,
                                     goal_id bigint,
                                     user_id bigint NOT NULL,
                                     CONSTRAINT transactions_type_check CHECK (((type)::text = ANY ((ARRAY['BUY'::character varying, 'SIP'::character varying, 'SELL'::character varying, 'SWP'::character varying])::text[])))
);


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_verification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_verification (
                                          id bigint NOT NULL,
                                          created_at timestamp(6) without time zone NOT NULL,
                                          entity_type character varying(255) NOT NULL,
                                          error_code character varying(255),
                                          is_verified boolean NOT NULL,
                                          ref character varying(255) NOT NULL,
                                          status character varying(255),
                                          updated_at timestamp(6) without time zone NOT NULL,
                                          value character varying(255),
                                          user_id bigint NOT NULL,
                                          CONSTRAINT user_verification_entity_type_check CHECK (((entity_type)::text = ANY ((ARRAY['READY_TO_INVEST'::character varying, 'NAME'::character varying, 'PAN'::character varying, 'DOB'::character varying])::text[]))),
    CONSTRAINT user_verification_error_code_check CHECK (((error_code)::text = ANY ((ARRAY['KYC_UNAVAILABLE'::character varying, 'KYC_INCOMPLETE'::character varying, 'UNKNOWN'::character varying, 'MISMATCH'::character varying, 'INVALID'::character varying, 'AADHAAR_NOT_LINKED'::character varying, 'UPSTREAM_ERROR'::character varying])::text[]))),
    CONSTRAINT user_verification_status_check CHECK (((status)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: user_verification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_verification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_verification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              aadhaar_last4 character varying(4),
                              birth_country character varying(255),
                              birth_place character varying(255),
                              client_code character varying(255),
                              created_at timestamp(6) without time zone NOT NULL,
                              date_of_birth timestamp(6) without time zone,
                              email character varying(255),
                              father_name character varying(255),
                              firebase_uid character varying(255) NOT NULL,
                              first_name character varying(255),
                              gender character varying(255),
                              income_slab character varying(255),
                              income_source character varying(255),
                              is_active boolean NOT NULL,
                              is_pep boolean NOT NULL,
                              is_ready_to_invest boolean NOT NULL,
                              kyc_status character varying(255),
                              marital_status character varying(255),
                              nominee_status character varying(255) NOT NULL,
                              occupation character varying(255),
                              pan_number character varying(255),
                              phone_number character varying(255),
                              prefill_status character varying(255) NOT NULL,
                              role character varying(255) NOT NULL,
                              signature character varying(255),
                              updated_at timestamp(6) without time zone NOT NULL,
                              address_id bigint,
                              investor_id bigint,
                              CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'TRANSGENDER'::character varying])::text[]))),
    CONSTRAINT users_income_slab_check CHECK (((income_slab)::text = ANY ((ARRAY['BELOW_1_LAC'::character varying, 'ABOVE_1_LAC_UPTO_5_LAC'::character varying, 'ABOVE_5_LAC_UPTO_10_LAC'::character varying, 'ABOVE_10_LAC_UPTO_25_LAC'::character varying, 'ABOVE_25_LAC_UPTO_1_CRORE'::character varying, 'ABOVE_1_CRORE'::character varying])::text[]))),
    CONSTRAINT users_income_source_check CHECK (((income_source)::text = ANY ((ARRAY['SALARY'::character varying, 'BUSINESS_INCOME'::character varying, 'ANCESTRAL_PROPERTY'::character varying, 'RENTAL_INCOME'::character varying, 'PRIZE_MONEY'::character varying, 'ROYALTY'::character varying, 'OTHERS'::character varying])::text[]))),
    CONSTRAINT users_kyc_status_check CHECK (((kyc_status)::text = ANY ((ARRAY['UNKNOWN'::character varying, 'PENDING'::character varying, 'AADHAAR_PENDING'::character varying, 'E_SIGN_PENDING'::character varying, 'SUBMITTED'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT users_marital_status_check CHECK (((marital_status)::text = ANY ((ARRAY['MARRIED'::character varying, 'UNMARRIED'::character varying, 'OTHERS'::character varying])::text[]))),
    CONSTRAINT users_nominee_status_check CHECK (((nominee_status)::text = ANY ((ARRAY['UNKNOWN'::character varying, 'OPT_OUT'::character varying, 'COMPLETED'::character varying])::text[]))),
    CONSTRAINT users_occupation_check CHECK (((occupation)::text = ANY ((ARRAY['BUSINESS'::character varying, 'SERVICE'::character varying, 'PROFESSIONAL'::character varying, 'AGRICULTURE'::character varying, 'RETIRED'::character varying, 'HOUSEWIFE'::character varying, 'STUDENT'::character varying, 'OTHERS'::character varying, 'DOCTOR'::character varying, 'PRIVATE_SECTOR_SERVICE'::character varying, 'PUBLIC_SECTOR_SERVICE'::character varying, 'FOREX_DEALER'::character varying, 'GOVERNMENT_SERVICE'::character varying, 'UNKNOWN_OR_NOT_APPLICABLE'::character varying])::text[]))),
    CONSTRAINT users_prefill_status_check CHECK (((prefill_status)::text = ANY ((ARRAY['INCOMPLETE'::character varying, 'FAILED_WITH_INVALID_NAME_OR_PHONE_NUMBER'::character varying, 'UNKNOWN_FAILURE'::character varying, 'COMPLETED'::character varying, 'FAILED_WITH_INVALID_PHONE_NUMBER_FORAMATE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['STANDARD'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mfa_attempts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mfa_attempts ALTER COLUMN id SET DEFAULT nextval('public.mfa_attempts_id_seq'::regclass);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: app_versions app_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_versions
    ADD CONSTRAINT app_versions_pkey PRIMARY KEY (id);


--
-- Name: bank_details bank_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_details
    ADD CONSTRAINT bank_details_pkey PRIMARY KEY (id);


--
-- Name: basket_fund basket_fund_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.basket_fund
    ADD CONSTRAINT basket_fund_pkey PRIMARY KEY (basket_id, fund_id);


--
-- Name: baskets baskets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.baskets
    ADD CONSTRAINT baskets_pkey PRIMARY KEY (id);


--
-- Name: children children_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.children
    ADD CONSTRAINT children_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: education education_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.education
    ADD CONSTRAINT education_pkey PRIMARY KEY (id);


--
-- Name: folio folio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folio
    ADD CONSTRAINT folio_pkey PRIMARY KEY (id);


--
-- Name: funds funds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funds
    ADD CONSTRAINT funds_pkey PRIMARY KEY (id);


--
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);


--
-- Name: holdings holdings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holdings
    ADD CONSTRAINT holdings_pkey PRIMARY KEY (id);


--
-- Name: investors investors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investors
    ADD CONSTRAINT investors_pkey PRIMARY KEY (id);


--
-- Name: job_history job_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_history
    ADD CONSTRAINT job_history_pkey PRIMARY KEY (id);


--
-- Name: mfa_attempts mfa_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mfa_attempts
    ADD CONSTRAINT mfa_attempts_pkey PRIMARY KEY (id);


--
-- Name: mfa_sessions mfa_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mfa_sessions
    ADD CONSTRAINT mfa_sessions_pkey PRIMARY KEY (id);


--
-- Name: nominee nominee_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nominee
    ADD CONSTRAINT nominee_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: qrtz_blob_triggers qrtz_blob_triggers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_blob_triggers
    ADD CONSTRAINT qrtz_blob_triggers_pkey PRIMARY KEY (sched_name, trigger_name, trigger_group);


--
-- Name: qrtz_calendars qrtz_calendars_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_calendars
    ADD CONSTRAINT qrtz_calendars_pkey PRIMARY KEY (sched_name, calendar_name);


--
-- Name: qrtz_cron_triggers qrtz_cron_triggers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_cron_triggers
    ADD CONSTRAINT qrtz_cron_triggers_pkey PRIMARY KEY (sched_name, trigger_name, trigger_group);


--
-- Name: qrtz_fired_triggers qrtz_fired_triggers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_fired_triggers
    ADD CONSTRAINT qrtz_fired_triggers_pkey PRIMARY KEY (sched_name, entry_id);


--
-- Name: qrtz_job_details qrtz_job_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_job_details
    ADD CONSTRAINT qrtz_job_details_pkey PRIMARY KEY (sched_name, job_name, job_group);


--
-- Name: qrtz_locks qrtz_locks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_locks
    ADD CONSTRAINT qrtz_locks_pkey PRIMARY KEY (sched_name, lock_name);


--
-- Name: qrtz_paused_trigger_grps qrtz_paused_trigger_grps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_paused_trigger_grps
    ADD CONSTRAINT qrtz_paused_trigger_grps_pkey PRIMARY KEY (sched_name, trigger_group);


--
-- Name: qrtz_scheduler_state qrtz_scheduler_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_scheduler_state
    ADD CONSTRAINT qrtz_scheduler_state_pkey PRIMARY KEY (sched_name, instance_name);


--
-- Name: qrtz_simple_triggers qrtz_simple_triggers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_simple_triggers
    ADD CONSTRAINT qrtz_simple_triggers_pkey PRIMARY KEY (sched_name, trigger_name, trigger_group);


--
-- Name: qrtz_simprop_triggers qrtz_simprop_triggers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_simprop_triggers
    ADD CONSTRAINT qrtz_simprop_triggers_pkey PRIMARY KEY (sched_name, trigger_name, trigger_group);


--
-- Name: qrtz_triggers qrtz_triggers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_triggers
    ADD CONSTRAINT qrtz_triggers_pkey PRIMARY KEY (sched_name, trigger_name, trigger_group);


--
-- Name: reverse_penny_drops reverse_penny_drops_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reverse_penny_drops
    ADD CONSTRAINT reverse_penny_drops_pkey PRIMARY KEY (id);


--
-- Name: sip_modification_items sip_modification_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sip_modification_items
    ADD CONSTRAINT sip_modification_items_pkey PRIMARY KEY (id);


--
-- Name: sip_modifications sip_modifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sip_modifications
    ADD CONSTRAINT sip_modifications_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: users uk4yiq7pdiwjw8inhg1xy83nabx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk4yiq7pdiwjw8inhg1xy83nabx UNIQUE (firebase_uid);


--
-- Name: users uk6dswpara0g9j1iyg8fkymg2fo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dswpara0g9j1iyg8fkymg2fo UNIQUE (investor_id);


--
-- Name: nominee uk76nr427k2lw2cqyy2jsfkw9pl; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nominee
    ADD CONSTRAINT uk76nr427k2lw2cqyy2jsfkw9pl UNIQUE (nominee_address_id);


--
-- Name: users uk8e2x48wh958avjeqd9ngond9j; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk8e2x48wh958avjeqd9ngond9j UNIQUE (client_code);


--
-- Name: app_versions uk9ahptyknoywarkqdsxrqj0gt6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_versions
    ADD CONSTRAINT uk9ahptyknoywarkqdsxrqj0gt6 UNIQUE (platform);


--
-- Name: baskets ukdt8ifisd1i7rctupw6b4miyke; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.baskets
    ADD CONSTRAINT ukdt8ifisd1i7rctupw6b4miyke UNIQUE (title);


--
-- Name: children ukfii96rm50eah2ijbot0qbemy7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.children
    ADD CONSTRAINT ukfii96rm50eah2ijbot0qbemy7 UNIQUE (investor_id);


--
-- Name: users ukhbvhqvjgmhd5omxyo67ynvbyp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukhbvhqvjgmhd5omxyo67ynvbyp UNIQUE (address_id);


--
-- Name: user_verification user_verification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_verification
    ADD CONSTRAINT user_verification_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_baskets_basket_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_baskets_basket_type ON public.baskets USING btree (basket_type);


--
-- Name: idx_job_history_job_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_history_job_name ON public.job_history USING btree (job_name);


--
-- Name: idx_job_history_start_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_history_start_time ON public.job_history USING btree (start_time);


--
-- Name: idx_job_history_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_job_history_status ON public.job_history USING btree (status);


--
-- Name: idx_mfa_attempts_attempted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mfa_attempts_attempted_at ON public.mfa_attempts USING btree (attempted_at);


--
-- Name: idx_mfa_attempts_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mfa_attempts_session_id ON public.mfa_attempts USING btree (mfa_session_id);


--
-- Name: idx_mfa_sessions_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mfa_sessions_created_at ON public.mfa_sessions USING btree (created_at);


--
-- Name: idx_mfa_sessions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mfa_sessions_status ON public.mfa_sessions USING btree (status);


--
-- Name: idx_mfa_sessions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mfa_sessions_user_id ON public.mfa_sessions USING btree (user_id);


--
-- Name: idx_mfa_sessions_user_id_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mfa_sessions_user_id_status ON public.mfa_sessions USING btree (user_id, status);


--
-- Name: idx_qrtz_ft_inst_job_req_rcvry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_ft_inst_job_req_rcvry ON public.qrtz_fired_triggers USING btree (sched_name, instance_name, requests_recovery);


--
-- Name: idx_qrtz_ft_j_g; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_ft_j_g ON public.qrtz_fired_triggers USING btree (sched_name, job_name, job_group);


--
-- Name: idx_qrtz_ft_jg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_ft_jg ON public.qrtz_fired_triggers USING btree (sched_name, job_group);


--
-- Name: idx_qrtz_ft_t_g; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_ft_t_g ON public.qrtz_fired_triggers USING btree (sched_name, trigger_name, trigger_group);


--
-- Name: idx_qrtz_ft_tg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_ft_tg ON public.qrtz_fired_triggers USING btree (sched_name, trigger_group);


--
-- Name: idx_qrtz_ft_trig_inst_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_ft_trig_inst_name ON public.qrtz_fired_triggers USING btree (sched_name, instance_name);


--
-- Name: idx_qrtz_j_grp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_j_grp ON public.qrtz_job_details USING btree (sched_name, job_group);


--
-- Name: idx_qrtz_j_req_recovery; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_j_req_recovery ON public.qrtz_job_details USING btree (sched_name, requests_recovery);


--
-- Name: idx_qrtz_t_c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_c ON public.qrtz_triggers USING btree (sched_name, calendar_name);


--
-- Name: idx_qrtz_t_g; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_g ON public.qrtz_triggers USING btree (sched_name, trigger_group);


--
-- Name: idx_qrtz_t_j; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_j ON public.qrtz_triggers USING btree (sched_name, job_name, job_group);


--
-- Name: idx_qrtz_t_jg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_jg ON public.qrtz_triggers USING btree (sched_name, job_group);


--
-- Name: idx_qrtz_t_n_g_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_n_g_state ON public.qrtz_triggers USING btree (sched_name, trigger_group, trigger_state);


--
-- Name: idx_qrtz_t_n_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_n_state ON public.qrtz_triggers USING btree (sched_name, trigger_name, trigger_group, trigger_state);


--
-- Name: idx_qrtz_t_next_fire_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_next_fire_time ON public.qrtz_triggers USING btree (sched_name, next_fire_time);


--
-- Name: idx_qrtz_t_nft_misfire; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_nft_misfire ON public.qrtz_triggers USING btree (sched_name, misfire_instr, next_fire_time);


--
-- Name: idx_qrtz_t_nft_st; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_nft_st ON public.qrtz_triggers USING btree (sched_name, trigger_state, next_fire_time);


--
-- Name: idx_qrtz_t_nft_st_misfire; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_nft_st_misfire ON public.qrtz_triggers USING btree (sched_name, misfire_instr, next_fire_time, trigger_state);


--
-- Name: idx_qrtz_t_nft_st_misfire_grp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_nft_st_misfire_grp ON public.qrtz_triggers USING btree (sched_name, misfire_instr, next_fire_time, trigger_group, trigger_state);


--
-- Name: idx_qrtz_t_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qrtz_t_state ON public.qrtz_triggers USING btree (sched_name, trigger_state);


--
-- Name: holdings fk1c70rpdpy0ybvaab1uiibmvht; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holdings
    ADD CONSTRAINT fk1c70rpdpy0ybvaab1uiibmvht FOREIGN KEY (goal_id) REFERENCES public.goals(id);


--
-- Name: transactions fk1fs59dvaqiktnb1y8pdrb7sq7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk1fs59dvaqiktnb1y8pdrb7sq7 FOREIGN KEY (fund_id) REFERENCES public.funds(id);


--
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: order_items fk5usu31iiv7sjme9tx7rvvfpn8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk5usu31iiv7sjme9tx7rvvfpn8 FOREIGN KEY (fund_id) REFERENCES public.funds(id);


--
-- Name: payments fk6jd1048r182g6oyg68nw6vfg0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk6jd1048r182g6oyg68nw6vfg0 FOREIGN KEY (child_id) REFERENCES public.children(id);


--
-- Name: children fk6jxlkcfyym16emflaq0ak70pd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.children
    ADD CONSTRAINT fk6jxlkcfyym16emflaq0ak70pd FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: sip_modification_items fk6op2qbw1pch1eu89e3i3pgy14; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sip_modification_items
    ADD CONSTRAINT fk6op2qbw1pch1eu89e3i3pgy14 FOREIGN KEY (order_item_id) REFERENCES public.order_items(id);


--
-- Name: nominee fk7ddobditgjydnuw5wrchtsbbu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nominee
    ADD CONSTRAINT fk7ddobditgjydnuw5wrchtsbbu FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: transactions fk7x4gg5el0p36geu3o2iw646qu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk7x4gg5el0p36geu3o2iw646qu FOREIGN KEY (goal_id) REFERENCES public.goals(id);


--
-- Name: orders fk8aol9f99s97mtyhij0tvfj41f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk8aol9f99s97mtyhij0tvfj41f FOREIGN KEY (payment_id) REFERENCES public.payments(id);


--
-- Name: nominee fk8py8m1e0rdovsrcexw5p5xv1p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nominee
    ADD CONSTRAINT fk8py8m1e0rdovsrcexw5p5xv1p FOREIGN KEY (nominee_address_id) REFERENCES public.addresses(id);


--
-- Name: goals fk_goals_transferred_to_goal; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT fk_goals_transferred_to_goal FOREIGN KEY (transferred_to_goal_id) REFERENCES public.goals(id);


--
-- Name: mfa_attempts fk_mfa_attempts_session; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mfa_attempts
    ADD CONSTRAINT fk_mfa_attempts_session FOREIGN KEY (mfa_session_id) REFERENCES public.mfa_sessions(id) ON DELETE CASCADE;


--
-- Name: holdings fka2qgy93i8erhvbf7kmx138mfd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holdings
    ADD CONSTRAINT fka2qgy93i8erhvbf7kmx138mfd FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: goals fkb1mp6ulyqkpcw6bc1a2mr7v1g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT fkb1mp6ulyqkpcw6bc1a2mr7v1g FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: sip_modifications fkc7r1cxie4hxquw7acrgs95d5v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sip_modifications
    ADD CONSTRAINT fkc7r1cxie4hxquw7acrgs95d5v FOREIGN KEY (sip_order_id) REFERENCES public.orders(id);


--
-- Name: children fkd74aj6xk8whxyst1hty2v1trr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.children
    ADD CONSTRAINT fkd74aj6xk8whxyst1hty2v1trr FOREIGN KEY (investor_id) REFERENCES public.investors(id);


--
-- Name: goals fkdp2tm6159sp8ktuk34x0sapen; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT fkdp2tm6159sp8ktuk34x0sapen FOREIGN KEY (child_id) REFERENCES public.children(id);


--
-- Name: transactions fke0msyjgy7q55xqi0gk3jod5wl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fke0msyjgy7q55xqi0gk3jod5wl FOREIGN KEY (folio_id) REFERENCES public.folio(id);


--
-- Name: users fke8vydtk7hf0y16bfm558sywbb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fke8vydtk7hf0y16bfm558sywbb FOREIGN KEY (address_id) REFERENCES public.addresses(id);


--
-- Name: payments fkgsrve4778bxryrrm19f69kmst; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkgsrve4778bxryrrm19f69kmst FOREIGN KEY (investor_id) REFERENCES public.investors(id);


--
-- Name: payments fkh72a76epqdd7d84oufr1jylsq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkh72a76epqdd7d84oufr1jylsq FOREIGN KEY (bank_id) REFERENCES public.bank_details(id);


--
-- Name: order_items fkhx6gswhearm3wj5sy50ypcyg5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkhx6gswhearm3wj5sy50ypcyg5 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: holdings fki491yks74radun4236cyt3gb7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holdings
    ADD CONSTRAINT fki491yks74radun4236cyt3gb7 FOREIGN KEY (fund_id) REFERENCES public.funds(id);


--
-- Name: sip_modification_items fkidd9il5nyrt8dqb85gtr4irnc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sip_modification_items
    ADD CONSTRAINT fkidd9il5nyrt8dqb85gtr4irnc FOREIGN KEY (modification_id) REFERENCES public.sip_modifications(id);


--
-- Name: folio fkixe4djnp5wy1lccvoffp357u7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folio
    ADD CONSTRAINT fkixe4djnp5wy1lccvoffp357u7 FOREIGN KEY (fund_id) REFERENCES public.funds(id);


--
-- Name: payments fkj94hgy9v5fw1munb90tar2eje; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkj94hgy9v5fw1munb90tar2eje FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: goals fkjl8lk2tiuuu80h3rxwe0xj7g5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT fkjl8lk2tiuuu80h3rxwe0xj7g5 FOREIGN KEY (education_id) REFERENCES public.education(id);


--
-- Name: folio fklgdj2m27yi0ujr4ry4m1850vm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folio
    ADD CONSTRAINT fklgdj2m27yi0ujr4ry4m1850vm FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bank_details fkllq7g73te9fv5skfgttg7027x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_details
    ADD CONSTRAINT fkllq7g73te9fv5skfgttg7027x FOREIGN KEY (investor_id) REFERENCES public.investors(id);


--
-- Name: holdings fkm16k4qonajcly192wk7tmtwtg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holdings
    ADD CONSTRAINT fkm16k4qonajcly192wk7tmtwtg FOREIGN KEY (child_id) REFERENCES public.children(id);


--
-- Name: basket_fund fkm1bulbequshyb1xfkioxn8780; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.basket_fund
    ADD CONSTRAINT fkm1bulbequshyb1xfkioxn8780 FOREIGN KEY (fund_id) REFERENCES public.funds(id);


--
-- Name: orders fkm1nop2lcc64v8bd5f7l03wstu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkm1nop2lcc64v8bd5f7l03wstu FOREIGN KEY (goal_id) REFERENCES public.goals(id);


--
-- Name: users fkn51g5w5cwt799f9xmgx6g0qog; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkn51g5w5cwt799f9xmgx6g0qog FOREIGN KEY (investor_id) REFERENCES public.investors(id);


--
-- Name: goals fknlefdneh917xb1mkqrl2eg03; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT fknlefdneh917xb1mkqrl2eg03 FOREIGN KEY (basket_id) REFERENCES public.baskets(id);


--
-- Name: holdings fko0m56qvi5yyl5ikolvm7ih20o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holdings
    ADD CONSTRAINT fko0m56qvi5yyl5ikolvm7ih20o FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: orders fkotocci9mwc2adiliv28s8asag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkotocci9mwc2adiliv28s8asag FOREIGN KEY (investor_id) REFERENCES public.investors(id);


--
-- Name: basket_fund fkp88o4c3oc7abqr2ehsh2g4agi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.basket_fund
    ADD CONSTRAINT fkp88o4c3oc7abqr2ehsh2g4agi FOREIGN KEY (basket_id) REFERENCES public.baskets(id);


--
-- Name: bank_details fkqkekmr716vpixkah9ufxbun81; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bank_details
    ADD CONSTRAINT fkqkekmr716vpixkah9ufxbun81 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: folio fkqkl8bwk75c62faxhjct3ltqk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folio
    ADD CONSTRAINT fkqkl8bwk75c62faxhjct3ltqk FOREIGN KEY (investor_id) REFERENCES public.investors(id);


--
-- Name: transactions fkqwv7rmvc8va8rep7piikrojds; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkqwv7rmvc8va8rep7piikrojds FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_verification fktj9xd3vagu4sh7xk3ep9c2wx6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_verification
    ADD CONSTRAINT fktj9xd3vagu4sh7xk3ep9c2wx6 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: qrtz_blob_triggers qrtz_blob_triggers_sched_name_trigger_name_trigger_group_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_blob_triggers
    ADD CONSTRAINT qrtz_blob_triggers_sched_name_trigger_name_trigger_group_fkey FOREIGN KEY (sched_name, trigger_name, trigger_group) REFERENCES public.qrtz_triggers(sched_name, trigger_name, trigger_group);


--
-- Name: qrtz_cron_triggers qrtz_cron_triggers_sched_name_trigger_name_trigger_group_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_cron_triggers
    ADD CONSTRAINT qrtz_cron_triggers_sched_name_trigger_name_trigger_group_fkey FOREIGN KEY (sched_name, trigger_name, trigger_group) REFERENCES public.qrtz_triggers(sched_name, trigger_name, trigger_group);


--
-- Name: qrtz_simple_triggers qrtz_simple_triggers_sched_name_trigger_name_trigger_group_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_simple_triggers
    ADD CONSTRAINT qrtz_simple_triggers_sched_name_trigger_name_trigger_group_fkey FOREIGN KEY (sched_name, trigger_name, trigger_group) REFERENCES public.qrtz_triggers(sched_name, trigger_name, trigger_group);


--
-- Name: qrtz_simprop_triggers qrtz_simprop_triggers_sched_name_trigger_name_trigger_grou_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_simprop_triggers
    ADD CONSTRAINT qrtz_simprop_triggers_sched_name_trigger_name_trigger_grou_fkey FOREIGN KEY (sched_name, trigger_name, trigger_group) REFERENCES public.qrtz_triggers(sched_name, trigger_name, trigger_group);


--
-- Name: qrtz_triggers qrtz_triggers_sched_name_job_name_job_group_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qrtz_triggers
    ADD CONSTRAINT qrtz_triggers_sched_name_job_name_job_group_fkey FOREIGN KEY (sched_name, job_name, job_group) REFERENCES public.qrtz_job_details(sched_name, job_name, job_group);


--
-- PostgreSQL database dump complete
--
