CREATE TABLE nominee
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    relationship     VARCHAR(255)                            NOT NULL,
    dob              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    pan              VARCHAR(255),
    email            VARCHAR(255),
    address          VARCHAR(255),
    guardian_name    VARCHAR(255),
    guardian_email   VARCHAR(255),
    guardian_pan     VARCHAR(255),
    guardian_address VARCHAR(255),
    allocation       INTEGER                                 NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_nominee PRIMARY KEY (id)
);

ALTER TABLE nominee
    ADD CONSTRAINT FK_NOMINEE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE nominee
    ADD ref VARCHAR(255);

ALTER TABLE users
    ADD nominee_status VARCHAR(255);