export const QUERY_KEYS = {
  user: "user",
  userSignature: "userSignature",
  children: "children",
  education: "education",
  bankAccounts: "bankAccounts",
  goals: "goals",
  educationGoals: "educationGoals",
  superFDGoals: "superFDGoals",
  goal: "goal",
  pendingActivities: "pendingActivities",
  pendingOrders: "pendingOrders",
  portfolio: "portfolio",
  payment: "payment",
  sipOrders: "sipOrders",
  transactions: "transactions",
  fundAllocations: "fundAllocations",
  basket: "basket",
  nominees: "nominees",
  preVerification: "preVerification",
};
